force-app/main/default/objects/Box_Jwt_Connection__c/Box_Jwt_Connection__c.object-meta.xml
<CustomObject>
    <label>Box Jwt Connection</label>
    <pluralLabel>Box Jwt Connections</pluralLabel>
    <nameField>
        <label>Box Jwt Connection Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Box_Jwt_Connection__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>Client ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Box_Jwt_Connection__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <label>Client Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Box_Jwt_Connection__c/fields/Connection_Name__c.field-meta.xml
<CustomField>
    <fullName>Connection_Name__c</fullName>
    <label>Connection Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Box_Jwt_Connection__c/fields/Enterprise_ID__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_ID__c</fullName>
    <label>Enterprise ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Box_Jwt_Connection__c/fields/Is_Default__c.field-meta.xml
<CustomField>
    <fullName>Is_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Box_Jwt_Connection__c/fields/Private_Key__c.field-meta.xml
<CustomField>
    <fullName>Private_Key__c</fullName>
    <label>Private Key</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Box_Jwt_Connection__c/fields/Public_Key_ID__c.field-meta.xml
<CustomField>
    <fullName>Public_Key_ID__c</fullName>
    <label>Public Key Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BoxConnection.cls
public with sharing class BoxConnection {
    public static final String HEADER_CONTENT_TYPE = 'Content-Type';
    public static final String HEADER_APPLICATION_ENCODED = 'application/x-www-form-urlencoded';
    public static final String TOKEN_URL_STRING = 'https://api.box.com/oauth2/token';

    private static BoxConnection instance = null;
    public BoxPlatformApiConnection api { get; private set; }
    public String accessToken { get; private set; }

    private BoxConnection() {
        List<Box_Jwt_Connection__c> boxJwtConnectionList = [SELECT Connection_Name__c, Is_Default__c, Public_Key_ID__c, Client_ID__c, Client_Secret__c, Enterprise_ID__c, Private_Key__c FROM Box_Jwt_Connection__c];
        if(boxJwtConnectionList != null) {
            Box_Jwt_Connection__c boxJwtConnection = boxJwtConnectionList[0];
            System.debug('Found box jwt connection: ' + boxJwtConnection);
            String publicKeyId = boxJwtConnection.Public_Key_ID__c;
            String privateKey = boxJwtConnection.Private_Key__c;
            String enterpriseId = boxJwtConnection.Enterprise_ID__c;
            String clientId = boxJwtConnection.Client_ID__c;
            String clientSecret = boxJwtConnection.Client_Secret__c;

            BoxJwtEncryptionPreferences preferences = new BoxJwtEncryptionPreferences();
		    preferences.setPublicKeyId(publicKeyId);
		    preferences.setPrivateKey(privateKey);
		    api = BoxPlatformApiConnection.getAppEnterpriseConnection(enterpriseId, clientId, clientSecret, preferences);
            accessToken = api.getAccessToken();
        }
        else {
            System.debug('Box Application Settings metadata not found!');
        }
    }

    public static BoxConnection getInstance() {
        if(instance == null) {
            instance = new BoxConnection();
        }
        return instance;
    }

    @AuraEnabled(cacheable=true)
    public static String exchangeToken(String parentToken, String scopes, String resource) {
        String downscopedToken;
        
        // Construct the JWT URL parameters
        String urlParameters = 
            String.format('subject_token={0}' +
       		'&subject_token_type=urn:ietf:params:oauth:token-type:access_token' +
            '&grant_type=urn:ietf:params:oauth:grant-type:token-exchange' +
            '&scope={1}', new String[] {parentToken, scopes});

        // Get a service account connection
        BoxConnection box = BoxConnection.getInstance();
        BoxPlatformApiConnection api = box.api;
        
        // Create the request object
        BoxApiRequest request = new BoxApiRequest(api, TOKEN_URL_STRING, BoxApiRequest.METHOD_POST);
        request.shouldAuthenticate = false;
        request.setBody(urlParameters);
        request.addHeader(HEADER_CONTENT_TYPE, HEADER_APPLICATION_ENCODED);
        request.setTimeout(api.getTimeout());
        
        // Issue the POST request and parse the response
        HttpResponse response = request.send();
        if (response.getStatus() == 'OK') {
            BoxGenericJsonObject authResponse = new BoxGenericJsonObject(response.getBody());
            downscopedToken = authResponse.getValue('access_token');
        } else {
            System.debug('BoxPlatformApiConnection unable to authenticate to generate tokens');
        }
        
        return downscopedToken;    
    }
}